# Generated by Django 2.0.1 on 2018-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
