# Generated by Django 2.0.1 on 2018-02-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose_phone', '0002_auto_20180201_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Номера телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
    ]
